server:
  port: 8084

spring:
  application:
    name: AUTH-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: TalentSyncSecretKeyForJWTSecurityAuthenticationSOA20262027VerySecureKey
  expiration: 86400000
